services:
  application:
    container_name: chronos-calendar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8081"
    env_file:
      - ./.env
    networks:
      - stack

networks:
  stack:
    name: stack
    driver: bridge