version: '27.3.1'
services:
  autotodo:
    build: .
    ports:
      - "9090:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - autotodo-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: db_auto_todo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    networks:
      - autotodo-network

networks:
  autotodo-network:
    driver: bridge
